### ISSUE TITLE
python samples placement of secret files

### ISSUE THREAD

**Issue by mg6maciej** [googlesamples/android-play-publisher-api#11]
When executing python samples from a different directory, e.g.

    python ci/basic_list_apks.py com.example.myapp

`client_secrets.json` is expected to be in the same directly as python script (i.e. `ci/`), but `androidpublisher.dat` is expected to be in the working directory.

Is there a way to control this, so `androidpublisher.dat` is looked up in the directory, where all other files are?

**Comment by JoseAlcerreca** [comment]
Check out the Google API Python client code 
https://github.com/google/google-api-python-client/blob/master/googleapiclient/sample_tools.py

Closing as this is out of the scope of this project.
