### ISSUE TITLE
Exception with android gradle tools 1.1.2

### ISSUE THREAD

**Issue by minakov** [googlesamples/android-play-publisher-api#17]
```
buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.1.2'
        classpath 'com.google.apis:google-api-services-androidpublisher:v2-rev16-1.19.1'
    }
}
```

```
Error:(1, 0) Expecting a stack map frame
Exception Details:
  Location:
    com/android/build/gradle/internal/TaskManager.getExtension()Lcom/android/build/gradle/BaseExtension; @5: aconst_null
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: 2ab4 005e b001 b0                      
```

**Comment by JoseAlcerreca** [comment]
What instructions have you followed to create that build config?

**Comment by bluesliverx** [comment]
I built a gradle plugin to build off of the google play publisher samples, and it's having the same issue apparently: https://github.com/bluesliverx/gradle-android-publisher/issues/6.  Any ideas?

**Comment by JoseAlcerreca** [comment]
Use the sample as a base for your project, dependencies should not be defined that way.

**Comment by bluesliverx** [comment]
@JoseAlcerreca, I'm sorry but I don't think that's the right answer.  Including the JAR file into the libs directory of a project will fix this (I believe), but I think the actual failure is due to a conflicting or bad google-api-client JAR that is pulled in by google-api-services-androidpublisher.  @minakov, try:

```
classpath('com.google.apis:google-api-services-androidpublisher:v2-rev16-1.19.1') {
  exclude module:'google-api-client'
}
```

**Comment by JoseAlcerreca** [comment]
Thanks guys! I'm afraid that's out of the scope of this project, which just hosts the sample code, but I'll contact the team.

**Comment by bluesliverx** [comment]
For those who are interested, this is solved by the following:

```
classpath('com.google.apis:google-api-services-androidpublisher:v2-rev16-1.19.1') {
    exclude module:'google-api-client'
}
classpath 'com.google.api-client:google-api-client:1.20.0'
```

Basically as long as you include the updated google-api-client, it works just fine.  Note: you may need to also update the androidpublisher dep to the latest as well.

**Comment by bluesliverx** [comment]
Pushed 0.5, but the travis builds are untested for release versions, I'll try to keep my eye on it.
