### ISSUE TITLE
Is it possible to promote to beta using the api?

### ISSUE THREAD

**Issue by YoniH** [googlesamples/android-play-publisher-api#20]
If it is, I would be happy to see a code sample

**Comment by orrc** [comment]
Yes, though as far as I recall, the API doesn't help you with this — you need to explicitly patch the version code(s) on the alpha track to remove the code(s) you want to promote to beta, and then reassign those version codes to the beta track before committing.

**Comment by YoniH** [comment]
Thanks, it works :)
