### ISSUE TITLE
Got 403 updating old alpha apk to new beta apk

### ISSUE THREAD

**Issue by drdrdr** [googlesamples/android-play-publisher-api#26]
Upload apk with version 11590 to alpha track.

Set TRACK = 'beta'

Run script
    + ./basic_upload_apks.py ru.bla.bla app-release.apk
     
    Version code 11591 has been uploaded
    Track beta is set for version code(s) [11591]
    Traceback (most recent call last):
      File "./basic_upload_apks_release.py", line 84, in <module>
        main(sys.argv)
      File "./basic_upload_apks_release.py", line 75, in main
        editId=edit_id, packageName=package_name).execute()
      File "oauth2client/_helpers.py", line 133, in positional_wrapper
        return wrapped(*args, **kwargs)
      File "googleapiclient/http.py", line 838, in execute
        raise HttpError(resp, content, uri=self.uri)
    googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/androidpublisher/v2/applications/ru.bla.bla/edits/11417089745524793338:commit?alt=json returned "Version 11590 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.">

Go to the developer console, promote old alpha apk 11590 to beta, run script again and got success.
Also manual uploading 11591 to the beta tab without promoting alpha 11590 to beta is also successful.

**Comment by orrc** [comment]
Yeah, that's how the API works, unfortunately. It doesn't do anything helpful for you, like the web console does — you must manually check the tracks and move around the version codes as necessary.

**Comment by drdrdr** [comment]
So is there is no way to deploy alpha-tested apks to beta-test or production using google play api?

**Comment by orrc** [comment]
Sure, like I was saying, you need to update the version codes assigned to the tracks. e.g. Open an edit session, set an empty list of version codes for the alpha track, set the appropriate version code in the beta track, then commit.

**Comment by drdrdr** [comment]
Ok, thank you. This way is acceptable.
