### ISSUE TITLE
it showing error in list apk page

### ISSUE THREAD

**Issue by ranjeetscience** [googlesamples/android-play-publisher-api#34]
Traceback (most recent call last):
  File "basic_list_apks.py", line 62, in <module>
    main(sys.argv)
  File "basic_list_apks.py", line 53, in main
    for apk in apks_result['apks']:
KeyError: 'apks'

**Comment by metou3** [comment]
Hi ranjeetscience, I have the same problem, how did you solve it?

**Comment by metou3** [comment]
{u'kind': u'androidpublisher#apksListResponse'}
KeyErrorTraceback (most recent call last)

print apks_result
for apk in apks_result['apks']:
print 'versionCode: %s, binary.sha1: %s' % (
apk['versionCode'], apk['binary']['sha1'])

KeyError: 'apks'
