### ISSUE TITLE
com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden

### ISSUE THREAD

**Issue by xjxuvup** [googlesamples/android-play-publisher-api#4]
I'm trying to run the java sample code,but I got the error.I have updated ApplicationConfig.java.I don't know why.Could anyone give me a hand? Thanks.

{
  "code" : 403,
  "errors" : [ {
    "domain" : "androidpublisher",
    "message" : "The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console.",
    "reason" : "projectNotLinked"
  } ],
  "message" : "The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console."
}

**Comment by DataGreed** [comment]
I still get the same error

**Comment by jagadish906** [comment]
can any one found the solution i too have the same issue

**Comment by LipiLee** [comment]
I think that official document should be updated.
When you create a service account, you should add a role **Other** - "**Subscribe with Google Developer**" in the "**2. Grant this service account access to project (optional)**"

And then in your Play Console, you can see the account you create.
