### ISSUE TITLE
Can't upload deobfuscation files

### ISSUE THREAD

**Issue by SGMcejo** [googlesamples/android-play-publisher-api#40]
I'm trying to upload the deobfuscation for an apk. But i always get some errors about the _deobfuscationFileType_. I can't find proper documentation about what i should enter there as well.

I tried the following:
`edits.Deobfuscationfiles().upload(appPackage, customAppEdit.id, apk.versionCode, "proguard").execute()`
Which leads in:
`{
  "code" : 500,
  "message" : null
}
`

If i provide the mime type (which you define as "Accepted Media MIME types" in your documentation):
`edits.Deobfuscationfiles().upload(appPackage, customAppEdit.id, apk.versionCode, "application/octet-stream").execute()`
Then it leads in:
`{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "location" : "deobfuscationFileType",
    "locationType" : "parameter",
    "message" : "Invalid string value: 'application/octet-stream'. Allowed values: [proguard]",
    "reason" : "invalidParameter"
  } ],
  "message" : "Invalid string value: 'application/octet-stream'. Allowed values: [proguard]"
}
`

I tried many other combinations as well but nothing works...
How can I use the api to upload the deobfuscation file?

**Comment by orrc** [comment]
I've heard multiple reports recently of the deobfuscation file upload API appearing to succeed, but silently it's failing — the file doesn't end up on Google Play.  So for it to return a 500 status code (i.e. server error) is new.

But while the entire publishing API is often unreliable, if this keeps occurring then it's certainly a problem on Google's end, and you should contact Google Play Developer Support asking them to fix it.

**Comment by dmarjanovic** [comment]
>deobfuscation file upload API appearing to succeed, but silently it's failing

Google has just fixed this so it should work fine now.

@SGMcejo this snippet worked for me:

>             // Upload mapping file to developer console
>            final String mappingPath = BasicUploadApk.class
>                    .getResource(ApplicationConfig.MAPPING_FILE_PATH)
>                    .toURI().getPath();
>            final AbstractInputStreamContent mappingFile =
>                    new FileContent(AndroidPublisherHelper.MIME_TYPE_MAPPING, new File(mappingPath));
>            DeobfuscationFilesUploadResponse deobfuscationFilesUploadResponse = edits.deobfuscationfiles()
>                    .upload(ApplicationConfig.PACKAGE_NAME,
>                            editId,
>                            apk.getVersionCode(),
>                            "proguard",
>                           mappingFile)
>                    .execute();

I was using it right after:
https://github.com/googlesamples/android-play-publisher-api/blob/master/v2/java/src/com/google/play/developerapi/samples/BasicUploadApk.java#L85

Constants are:
>    public static final String MIME_TYPE_MAPPING = "application/octet-stream";
>    public static final String MAPPING_FILE_PATH = "/resources/mapping.txt";

**Comment by SGMcejo** [comment]
@dmarjanovic thank you very much! that works like a charm now!

**Comment by srgiitd** [comment]
@dmarjanovic Is this working with V3 APIs also? I tried but didn't work for me. I'm getting this Exception:

> com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
{
  "code" : 404,
  "errors" : [ {
    "domain" : "androidpublisher",
    "message" : "Edit not found for this application.",
    "reason" : "editNotFound"
  } ],
  "message" : "Edit not found for this application."
}

**Comment by stephenrjohnson** [comment]
@srgiitd @dmarjanovic Did you ever get this working ?

**Comment by dmarjanovic** [comment]
I haven't try the code sample with v3 myself but it should work for sure since we're using it with Jenkins Android Publisher plugin based on v3 since its release 2.0 https://github.com/jenkinsci/google-play-android-publisher-plugin/releases

**Comment by stephenrjohnson** [comment]
I've trying the following

      odbs_response = (
            self.service.edits()
            .deobfuscationfiles()
            .upload(
                editId=edit_id,
                packageName=package_name,
                media_body=defob_file,
                media_mime_type="application/octet-stream",
                apkVersionCode=int(version_code),
                deobfuscationFileType="proguard",
            )
            .execute()
        )

and I keep getting returned "APK not found for the symbol file."

request is 

https://www.googleapis.com/upload/androidpublisher/v3/applications/(ourapp)/edits/17779307661168450862/apks/22/deobfuscationFiles/proguard?alt=json&uploadType=media

**Comment by d3n155** [comment]
Hey @stephenrjohnson
Did you get this working?
I get the following error since weeks now:
`googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/upload/androidpublisher/v3/applications/our.app/edits/01877575759615878359/apks/9171554/deobfuscationFiles/proguard?alt=json&uploadType=media returned "Symbol file invalid.">`

**Comment by stephenrjohnson** [comment]
Nope and had a few members of my team to take a look and it should work per what we can tell.
