### ISSUE TITLE
How can I get sales country with this API?

### ISSUE THREAD

**Issue by choiis** [googlesamples/android-play-publisher-api#58]
Hello I am Mr.Choi from south korea.
I'm supposed to get list of sales country to using publish api.
How can I get sales country with this API?

and I tried to get countryTargeting in tracks.
But getCountryTargetings method always returned null.
Why did the method return null, and What does countryTargeting means?

Thanks

**Comment by carstenhag** [comment]
Google hasn't made it available, albeit them having this as a json/protobuf api existing.
